component: mock-mv
part-of: mosip
activeProfileEnv: mz 
springConfigLabel:  1.1.5
configServerUrl: http://config-server.default:80/config
probe:
  initialDelay: 30  # Seconds
  period: 30 # Seconds
imagePullPolicy: Always

exportLogs: enabled  # Let filebeat export the logs

isGlowroot: present

dockerHub:
  private: False  
  keyname: dockerhubkey

services:
  mockmv:
    serviceName: mock-mv
    dockerImage: mosipid/mock-mv:1.1.5
    containerPort: 8081
    servicePort: 80
    ingressPath: /v1/mockmv
    healthUrl: /v1/mockmv/actuator/health
    podconfig:
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      replicas: 1
      resources:
            limits:
                  cpu: 400m
                  memory: 700Mi
            requests:
                  cpu: 200m
                  memory: 500Mi
domain: apps.mzuat.rnp.ma