---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.services.serviceName }}
  namespace: {{ .Release.Namespace }} 
spec:
  replicas: {{ .Values.services.podconfig.replicas }}  
  selector:
    matchLabels:
      app: {{ .Values.services.serviceName }}
  minReadySeconds: {{ .Values.services.podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.services.podconfig.maxUnavailable }}
      maxSurge: {{ .Values.services.podconfig.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.serviceName }} 
        exportLogs: {{ .Values.exportLogs }}
    spec:
      containers:
      - name: {{ .Values.services.serviceName }}
        image: {{ .Values.services.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{ $resources := .Values.services.podconfig.resources }}
        {{- include "resourcesDefinition" (dict "res" $resources) | indent 8 }}
        env:
        - name: hub_datasource_url_env
          value: {{ .Values.hub.datasource_url }}
        - name: hub_datasource_username_env
          value: {{ .Values.hub.datasource_username }}
        - name: hub_datasource_password_env
          value: {{ .Values.hub.datasource_password }}
        - name: hub_retry_count_env
          value: {{ .Values.hub.retry_count | quote}}
        - name: hub_retry_interval_env
          value: {{ .Values.hub.retry_interval | quote}}
        - name: hub_retry_backoff_factor_env
          value: {{ .Values.hub.retry_backofffactor | quote }}
        - name: hub_retry_max_wait_interval_env
          value: {{ .Values.hub.retry_maxwaitinterval | quote}}
        - name: hub_restart_republish_time_offset_env
          value: {{ .Values.hub.republish_time }}
        ports:
        - containerPort: {{ .Values.hub.port }} 
