name: websub # Will be used as service name too
services:
  serviceName: websub-service
  dockerImage: mosipid/websub-service:1.1.5
  servicePort: 80
  podconfig:
    maxSurge: 1
    maxUnavailable: 0
    minReadySeconds: 10
    replicas: 1

exportLogs: enabled  # Let filebeat export the logs

component: websub

imagePullPolicy: Always

domain: apps.mzuat.rnp.ma

hub:
  datasource_url: jdbc:postgresql://10.230.82.211:30090/mosip_websub 
  datasource_username: websubuser
  datasource_password: mosip123
  retry_count: 7
  retry_interval: 1000
  retry_backofffactor: 2.0
  retry_maxwaitinterval: 65000
  port: 9191
  republish_time: 2021-03-24T08:07:11.645Z
domain: apps.mzuat.rnp.ma