name: rnp-mv-backend # Will be used as service name too
docker:
  image: mosipid/sandbox-config-server:1.1.0
  containerPort: 8080
  servicePort: 80
jarName: kernel-config-server # Without .jar. Used locally for Docker
component: rnp-mv-backend

domain: app-console.apps.mzuat.rnp.ma
internalDomain: mzworker0.sb 

exportLogs: enabled  # Let filebeat export the logs

encryptKey: '' # Passed diretly via command line

sandboxPublicUrl: https://console.app-console.apps.mzuat.rnp.ma

gitRepo:
  uri: https://github.com/mosip/mosip-config
  searchFolders: sandbox
  private: False 
  username:     
  password: '' # Passed directly via command line

localRepo:
  enabled: True
  mountPath: /opt
  pv:
    name: rnp-mv-backend-pv
    size: 100Mi
  pvc:
    name: rnp-mv-backend-pvc
    size: 100Mi # Should not exceed pv size
  sc:
    name: "nfs-provisioner"
  nfs:
    server: 10.230.80.5
    path: /opt

