---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rnp-mv-backend-pv
  labels:
    name: rnp-mv-backend-pv
spec:
  storageClassName: "nfs-provisioner"
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "10.230.80.5"
    path: /opt
