name: keycloak
dockerImage: jboss/keycloak
dockerTag: 9.0.0 
keycloakUser: admin
keycloakPassword: '' # To be passed directly with helm command
domain: apps.mzuat.rnp.ma
internalDomain: mzworker0.sb 
keycloakExternalUrl: "https://console.apps.mzuat.rnp.ma/auth/"  
containerPort: 8080
exportLogs: enabled  # Let filebeat export the logs
servicePort: 80
db:
  name: keycloak
  host: 10.230.82.211
  port: 30090
  user: postgres
  password: ''  # Passed from helm directly 
ingress:
   namespace: default

services:
  keycloak:
    podconfig: {maxSurge: 1, maxUnavailable: 0, minReadySeconds: 10, replicas: 1}
 