component: print
part-of: mosip
activeProfileEnv: mz 
springConfigLabel:  1.1.5
configServerUrl: http://config-server.default:80/config
artifactoryUrl: http://artifactory-service.default:80/ 
iamAdapterUrl: http://artifactory-service.default:80/artifactory/libs-release-local/io/mosip/kernel/kernel-auth-adapter.jar
probe:
  initialDelay: 30  # Seconds
  period: 30 # Seconds
imagePullPolicy: Always

exportLogs: enabled  # Let filebeat export the logs

isGlowroot: absent 

dockerHub:
  private: False  
  keyname: dockerhubkey

services:
  print:
    serviceName: print-service
    dockerImage: mosipid/print:1.1.5
    containerPort: 8088
    servicePort: 80
    ingressPath: /v1/print
    healthUrl: /v1/print/actuator/health
    podconfig:
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      replicas: 1
domain: apps.mzuat.rnp.ma