clusterDomain: cluster.local
logRetentionBytes: _1073741824
defaultReplicationFactor: 3
offsetsTopicReplicationFactor: 3
transactionStateLogReplicationFactor: 3
numPartitions: 20
replicaCount: 5
sidecars: {}
autoCreateTopicsEnable: true

persistence:
  enabled: true
  storageClass: nfs-provisioner
  accessModes:
    - ReadWriteOnce
  size: 8Gi

zookeeper:
  replicaCount: 5
  persistence:
    enabled: true
    storageClass: nfs-provisioner
    size: 2Gi