name: activemq
docker:
  image:  mosipdev/activemq:1.1.3
  containerPort: 61616
  nodeport: 30616
  min-memory: 512
  max-memory: 2048
  storeusage: 16 gb
  tempusage: 8 gb
  webPort: 8161
  servicePort: 80
services:
  activemq:
    podconfig:
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      replicas: 1

adminPassword: '' # Defined diretly in helm command 

imagePullPolicy: Always 

exportLogs: enabled  # Let filebeat export the logs

sc:
  name: "nfs-provisioner"
pv:
  name: activemq
  size: 500Mi  
pvc:
  name: activemq
  size: 500Mi 

mountPath: /data/activemq  # path inside docker

nfs:
  server: 10.230.80.5 
  path: /srv/nfs/mosip/activemq/
domain: apps.mzuat.rnp.ma