component: datashare
part-of: mosip
activeProfileEnv: mz 
springConfigLabel:  1.1.5
configServerUrl: http://config-server.default:80/config
artifactoryUrl: http://artifactory-service.default:80/ 
iamAdapterUrl: http://artifactory-service.default:80/artifactory/libs-release-local/io/mosip/kernel/kernel-auth-adapter.jar
exportLogs: enabled  # Let filebeat export the logs

probe:
  initialDelay: 30  # Seconds
  period: 30 # Seconds
imagePullPolicy: Always

isGlowroot: absent 

dockerHub:
  private: False  
  keyname: dockerhubkey

services:
  datashare:
    serviceName: datashare-service
    dockerImage: mosipid/data-share-service:1.1.5
    containerPort: 8097
    servicePort: 80
    ingressPath: /v1/datashare
    healthUrl: /v1/datashare/actuator/health
    podconfig:
      java_opts: -Xms500M -Xmx500M
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      replicas: 1
domain: apps.mzuat.rnp.ma