name: artifactory-service
docker:
  service: artifactory-service
  image: mosipid/artifactory-server:1.1.5
  containerPort: 80
imagePullPolicy: Always

dockerHub:
  private: False  
  keyname: dockerhubkey

services:
  artifactory:
    podconfig: {maxSurge: 1, maxUnavailable: 0, minReadySeconds: 10, replicas: 1}


exportLogs: enabled  # Let filebeat export the logs
domain: apps.mzuat.rnp.ma