apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.volumeName }} 
  labels:
    name: {{ .Values.persistence.volumeName }} 
spec:
  storageClassName: "nfs-provisioner"
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  nfs:
    server:  {{ .Values.persistence.nfs.server }}
    path: {{ .Values.persistence.nfs.path }} 
