name: clamav
docker:
  image: mkodockx/docker-clamav:latest
  containerPort: 3310
imagePullPolicy: IfNotPresent

services:
  clamav:
    podconfig:
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      replicas: 1

exportLogs: enabled  # Let filebeat export the logs


