name: postgres
port: 80
user: postgres 
password: '' # To be passed directly with helm command
nfs:  # Must match nfs server params defined via Ansible
  server: 10.230.80.5 
  path: /srv/nfs/mosip/postgres
pvc:
  name: postgres-pvc
  size: 10Gi
pv:
  name: postgres-pv
  size: 10Gi
sc: 
  name: ""

exportLogs: enabled  # Let filebeat export the logs

resources:
  requests:
    memory: 512Mi 
    cpu: 250m 
docker:
  image: postgres
  tag: 12.2
  containerPort: 5432
nodePort: 30090
maxConnections: 1000 
nodeAffinity:
  enabled: False
  node: mzworker0.sb
  taint:
    key: postgres
    value: only

services:
  postgres:
    podconfig:
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      replicas: 1
