apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
     kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "console.{{ .Values.domain}}"
    http:
      paths:
      - path: /activemq/admin
        backend:
          serviceName: {{ .Values.name }}
          servicePort: {{ .Values.docker.webPort }}
  tls:
  - hosts:
    - "console.{{ .Values.domain}}"
    secretName: uat-cert