# Separate ingress for pktserver as the url rewrite path
# is different 
    
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pktserver-ingress
  namespace: {{ .Values.ingress.namespace }}
  annotations:
    ingress.kubernetes.io/class: nginx
      
spec:
  rules:
  - host: "console.{{ .Values.domain}}"
    http:
      paths:
      - path: /registrationprocessor/v1/dmzpacketserver/
        backend:
          serviceName: {{ .Values.services.pktserver.serviceName }}
          servicePort: {{ .Values.services.pktserver.ports.servicePort }}
  tls:
  - hosts:
    - "console.{{ .Values.domain}}"
    secretName: uat-cert
